### ISSUE TITLE
Change name of this repo to `pypyr-to-invoke-comparison-example`

### ISSUE THREAD

**Issue by vlcinsky** [pypyr/pyinvoke-comparison-example#1]
Current name of this repo `pyinvoke-comparison-example` has problems:
- `pyinvoke` is obsolete python package, the example is based on recent `invoke` package
- having `pypyr` in name could draw attention to the visitor better.

@yaythomas I am not sure, if I could do such a change.

**Comment by yaythomas** [comment]
great idea! 🌟 you're a maintainer on this repo, so I'm not actually sure if that means you can rename it - just in case it doesn't let you, I just did as you recommended!
